
CREATE DATABASE qlbh;

-- Sử dụng cơ sở dữ liệu
USE qlbh;

-- Tạo bảng NHANVIEN
CREATE TABLE NHANVIEN (
  MaNV INT PRIMARY KEY,
  HoNV VARCHAR(100),
  TenNV VARCHAR(100),
  GioiTinh TINYINT,
  NgaySinh DATETIME,
  DiaChi VARCHAR(255),
  DienThoai VARCHAR(10)
);

-- Tạo bảng KHACHANG
CREATE TABLE KHACHANG (
  MaKH INT PRIMARY KEY,
  HoTenKH VARCHAR(100),
  DiaChi VARCHAR(255),
  DienThoai VARCHAR(10)
);

-- Tạo bảng HOADON
CREATE TABLE HOADON (
  MaHD INT PRIMARY KEY,
  MaKH INT,
  MaNV INT,
  NgayLapHD DATETIME,
  NgayNhanHang DATETIME,
  FOREIGN KEY (MaKH) REFERENCES KHACHANG(MaKH),
  FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);