CREATE DATABASE Quan_Ly_Ban_Hang;
USE Quan_Ly_Ban_Hang;

CREATE TABLE NHANVIEN (
    MaNV VARCHAR(6) NOT NULL,
    HoNV VARCHAR(30) NOT NULL,
    TenNV VARCHAR(12) NOT NULL,
    GioiTinh BOOLEAN,
    NgaySinh DATE NOT NULL,
    DiaChi VARCHAR(50),
    DienThoai VARCHAR(10),
    PRIMARY KEY (MaNV)
);
INSERT INTO NHANVIEN (MaNV, HoNV, TenNV, GioiTinh, NgaySinh, DiaChi, DienThoai) VALUES 
('1', 'Lê văn', 'Tám', 1, '1965-10-12', '45 Trần Phú', '86452345'), 
('2', 'Trần thị', 'Lan', 0, '1970-10-20', 'Nguyễn Trãi Q5', ''), 
('3', 'Tạ thành', 'Tâm', 1, '1965-12-10', '20 Võ thị Sáu', '85656666'), 
('4', 'Ngô Thanh', 'Sơn', 1, '1950-12-20', '122 Trần Phú', ''), 
('5', 'Lê thị', 'Thủy', 0, '1970-10-10', '25 Ngô Quyền', '97654123');
SELECT * FROM NHANVIEN;




CREATE TABLE KHACHHANG (
    MaKH VARCHAR(6) NOT NULL,
    HoTenKH VARCHAR(40) NOT NULL,
    DiaChi VARCHAR(50),
    DienThoai VARCHAR(10),
    PRIMARY KEY (MaKH)
);
INSERT INTO KHACHHANG (MaKH, HoTenKH, DiaChi, DienThoai) VALUES
('B145', 'Cửa Hàng số 2 Q4', '20 Trần Phú Q2', '86547893'),
('D100', 'Công Ty Cổ Phần Đầu tư', '22 Ngô Quyền Q5', '86123564'),
('L010', 'Cửa Hàng Bách Hóa Q1', '155 Trần Hưng Đạo', '85456123'),
('S001', 'Công Ty XNK Hoa Hồng', '123 Trần Phú', '8356423'),
('S002', 'Công Ty VHP Tân Bình', '123 Trần Phú', '8554545');
SELECT * FROM KHACHHANG;




CREATE TABLE HOADON (
    MaHD VARCHAR(6) NOT NULL,
     MaKH VARCHAR(6),
    MaNV VARCHAR(6),
    NgayLapHD DATE NOT NULL,
 NgayNhanHang DATE NOT NULL,
    PRIMARY KEY (MaHD),
    FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);
-- ALTER TABLE HOADON
--   DROP COLUMN TongTien;
--   ALTER TABLE HOADON
--   ADD COLUMN NgayNhanHang DATETIME NOT NULL;
--   ALTER TABLE HOADON MODIFY COLUMN   MaKH
--   VARCHAR(6) AFTER MaHD; 
--   ALTER TABLE HOADON MODIFY COLUMN   MaNV
--   VARCHAR(6) AFTER MaKH;

INSERT INTO HOADON(MaHD,MaKH,MaNV,NgayLapHD,NgayNhanHang)VALUES
(1,'S001',1,'28/06/1999','10/07/1999');

CREATE TABLE SANPHAM (
    MaSP VARCHAR(6) NOT NULL,
    TenSP VARCHAR(50) NOT NULL,
    DonGia DECIMAL(10,2) NOT NULL CHECK (DonGia > 0),
    DonViTinh VARCHAR(10),
    PRIMARY KEY (MaSP)
);

CREATE TABLE CHITIETHD (
    MaHD VARCHAR(6) NOT NULL,
    MaSP VARCHAR(6) NOT NULL,
    SoLuong INT NOT NULL CHECK (SoLuong > 0),
    PRIMARY KEY (MaHD, MaSP),
    FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD),
    FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

